services:
  - type: web
    name: axon-sate-api
    env: python
    region: ohio 
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: HMAC_SECRET_KEY
        sync: false